let patterns = [

  // the first two patterns must be kept at the top of the list so they can easily be handled as a special case
  'cet(ear)?yl alcohol',
  'ceteareth[\- ]20',

  '1-acetoxyhexadecane',
  '1-hexadecanol( acetate)?',
  'acetic acid hexadecyl ester',
  'acetylated lanolin( alcohol)?',
  'acetylated wool (fat|wax)',
  'adansonia digitata l.',
  'agar',
  'ahnfeltiopsis concinna extract',
  'alaria esculenta extract',
  'alga bladderwrack',
  'algae( extract)?',
  'algin(ate)?',
  'alginic acid',
  'aphanothece sacrum polysaccharide',
  'arthrospira plantensis',
  'ascophyllum nodosum extract',
  'asparagopsis armata extract',
  'baobab',
  'beeswax',
  'bismuth',
  'bryopsis africana',
  'butyl (octadecanoate|stearate|stearic acid)',
  '(butyrospermum parkii|shea|butyrospermum|parkii)( butter)?',
  'cacao seed butter',
  'capea biruncinata var. (denuda|elongata) sonder',
  'carastay c',
  '(carrageenan|chondrus( crispus)?|irish)( (moss|gum))?( extract)?',
  'caulerpa (lentillifera|filiformis)( extract)?',
  'cera (alba|bianca|flava|olea)',
  'cetearyl alcohol \\+ ceteareth 20',
  'cetyl (acetate|alcohol)',
  'chaetomorpha linum \\(aerea\\) cladophora radiosa',
  'chlamydomonas reinhardtii extract',
  'chlorella',
  'chlorophyceae',
  'cladophora cf. subsimplex',
  'cladosiphon okamuranus extract',
  'coal tar',
  'cocoa butter',
  'coco-capr(yl)?ate',
  '(cocos nucifera|coconut) ( seed)?(oil|alkanes|butter|extract)',
  'coenochloris signiensis extract',
  'colloidal sulfur',
  'corallina officinalis extract',
  'corn( oil)?',
  'creosote',
  'cystoseira tamariscifolia extract',
  'd ?&? ?c red #?(17|21|3|30|36)',
  'decyl ?oleate',
  'dicotyledons succinate',
  'dictyopteris membranacea',
  'dictyopteris polypodioides',
  'di(ethylhexyl|octyl) sodium sulfosuccinate',
  'diisooctyl succinate',
  'dilsea carnosa extract',
  'dioctyl succinate',
  'disodium laureth sulfosuccinate',
  'disodium monooleamido',
  'disodium monooleamido( peg[\- ]2 sulfosuccinate)?',
  'disodium oleamido peg-2 sulfosuccinate',
  'dodec((an)?oic|ylic) acid',
  'dunaliella salina extract',
  'duodecylic acid',
  'durvillaea antarctica extract',
  'ecklonia (cava|radiata)( extract)?',
  'enteromorpha compressa extract',
  'ethoxylated lanolin',
  'ethylhexyl (palmitate|stearate)',
  'eucheuma spinosum extract',
  'fucoxanthin',
  'fucus (serratus|vesiculosus)',
  'gamtae extract',
  'gelidiella acerosa extract',
  'gelidium amansii extract',
  'gigartina stellata extract',
  'glyceryl[\- ]3 diisostearate',
  'glyceryl monostearate',
  'glyceryl stearate se',
  'glycine max',
  '(glycine soja|soybean) oil',
  '(gossypium herbaceum|cotton|awws|sclerocarya birrea) seed oil',
  'gracilariopsis chorda extract',
  'haematococcus pluvialis( extract)?',
  'haslea ostrearia extract',
  'hexadecanol acetate',
  'hexadecyl acetate',
  'hexadecyl alcohol',
  'himanthalia elongata extract',
  'hizikia fusiforme extract',
  'hydrogenated (vegetable|sunflower|castor|jojoba) (seed )?oil',
  'hydrolyzed rhodophycea extract',
  'hydrous magnesium silicate',
  'hypneaceae extract',
  'hypnea musciformis extract',
  'isocetyl (alcohol|stearate)',
  'isodecyl oleate',
  'isohexadecanol',
  'isohexadecyl (stearate|alcohol)',
  'isooctadecyl isooctadecanoate',
  'isopalmit(ic|yl) alcohol',
  'isopropyl (iso(stear|decano)|linol|myrist|palmit)ate',
  'isostearyl ((isostear|neopentano)ate)',
  'jania rubens extract',
  'jojoba wax',
  'kappaphycus alvarezii extract',
  'karite',
  'kelp',
  'kousou ekisu',
  'laminaria (digitata|saccharin[ae])( extract)?',
  'lanolin( alcohol)? acetate',
  'lanolin polyoxyethylene ether',
  'laureth[\- ](23|4)',
  'lauric acid',
  'laurostearic acid',
  'lcd',
  'linolate',
  'liquor carbonis detergens',
  'liquor picis carbonis',
  'lithothamnium calcareum powder',
  'lpc',
  'macroalgae',
  'macrocystis pyrifera extract',
  'mangifera indica seed butter',
  'mango butter',
  'marula( oil)?',
  'methylsilanol mannuronate',
  'mink oil',
  'moss',
  'myristate',
  'myristic acid',
  'myristyl( (lac|myris|propion)tate)?',
  'n-hexadecyl (alcohol|ethenoate)',
  'octadecanoic acid',
  'octadecyl heptanoate',
  'octyl (palmit|stear)ate',
  'oleth[\- ]3( phosphate)?',
  'oleyl alcohol',
  'palmaria palmata extract',
  'palmityl (acetate|alcohol)',
  'peg[\- ]16 lanolin',
  'peg[\- ]200 dilaurate',
  'peg[\- ]2 sulfosuccinate',
  'peg[\- ]75',
  'peg[\- ]8 stearate',
  'pelvetia canaliculata extract',
  'pes',
  'pg monostearate',
  'pgms',
  'phaeodactylum tricornutum extract',
  'phaeophyceae',
  'pix carbonis',
  'plankton',
  'polyethylene glycol (200|dodecyl ether|jojoba acid|lauryl ether|monododecyl ether|stearate)',
  'polyglyceryl[\- ]3[\- ]diisostearate',
  'polyoxyethylene lauryl ether',
  'polysiphonia elongata extract',
  'porphyra umbilicalis',
  'porphyridium( (cruentum extract|polysaccharide))?',
  'potassium (chloride|salt)',
  'ppg[\- ]2 myristyl( (ether )?propionate)',
  'propanoic acid',
  'propylene glycol monostearate',
  'pyrene coal tar pitch',
  '(red )?algae( extract)?',
  'rhodophyceae extract',
  'rhodophyta',
  'sargassum (filipendula|fusiforme) extract',
  'sclerocarya birrea',
  'sea fern',
  'seaweed',
  'sesame',
  'sesamum indicum',
  'shark liver oil',
  '(shark )?squal[ae]ne',
  'sheep alcohol',
  'simmondsia chinensis seed wax',
  'sles',
  'slo',
  'sls',
  'sodium alginate',
  'sodium alkylethersulfate',
  'sodium docusate',
  'sodium dodecyl sulphate',
  'sodium lauryl ether sulfate',
  'sodium laur(yl|eth) sulfate',
  'soja',
  'solulan 16',
  'sorbitan (mono)?oleate',
  'soy(bean)?( oil)?',
  'sphacelaria',
  'spirulina',
  'starch',
  'steareth[\- ]10',
  'stearic acid tea',
  'stearyl heptanoate',
  'sul(f|ph)ated (castor|jojoba) oil',
  'sulfosuccinate',
  'talc(um)?',
  'tea stearate',
  'tetradecanoic acid',
  'tetradecyl (lactate|myristate|propionate)',
  'theobroma( cocoa)?( seed)? (butter|oil)?',
  'triticum (aestivum|vulgare)',
  'turkey red oil',
  'ulva (fasciata|lactuca|rhacodes)',
  'undaria pinnatifida',
  'vegetable gelatin',
  'vitellaria paradoxa',
  'vulvic acid',
  'wakame',
  'wheat( germ (oil|glyceride))?',
  'wool (alcohol|fat)',
  'xanthophyta',
  'xyl(ene|itol)',
  'zea mays',
];

// Replace each space with a wildcard pattern for non-word characters.
// Also insert the same wildcard at the start and end of each pattern.
export default patterns.map(pattern => new RegExp('^\\s*?' + pattern + '\\s*?$', 'i'));
